# Generated by Django 4.2.3 on 2023-07-11 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movielog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movielog',
            name='log_time',
            field=models.DateTimeField(),
        ),
    ]
