# Generated by Django 4.2.3 on 2023-07-11 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movielog_log_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movielog',
            name='log_time',
            field=models.DateField(),
        ),
    ]
