# Generated by Django 4.2.3 on 2023-07-14 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_movielog_log_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='movielog',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
