# Generated by Django 4.2.3 on 2023-07-14 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_alter_movielog_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movielog',
            name='log_time',
            field=models.DateTimeField(verbose_name='I watched it on'),
        ),
        migrations.AlterField(
            model_name='movielog',
            name='seen',
            field=models.BooleanField(default=False, verbose_name='I have seen this film before'),
        ),
    ]
