# Generated by Django 4.2.3 on 2023-07-14 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_alter_movielog_log_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movielog',
            name='seen',
            field=models.BooleanField(verbose_name='I have seen this film before'),
        ),
    ]
