# Generated by Django 4.2.3 on 2023-07-14 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_alter_movielog_seen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movielog',
            old_name='movie',
            new_name='movie_name',
        ),
    ]
