# Generated by Django 4.2.3 on 2023-07-15 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_rename_movie_movielog_movie_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.ImageField(default='posters/default', upload_to='posters'),
        ),
        migrations.AddField(
            model_name='movie',
            name='poster_url',
            field=models.URLField(null=True),
        ),
    ]
