# Generated by Django 4.2.3 on 2023-07-19 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_alter_movie_poster_alter_movie_poster_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='poster',
        ),
    ]
