# Generated by Django 4.2.3 on 2023-07-28 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0015_remove_movie_poster'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movielog',
            options={'ordering': ['-log_time']},
        ),
    ]
